"""Council preview endpoint: runs the 7 specialists + moderator on the
current env state and returns the resulting CouncilDecision.

Picks a real OpenAI-compatible client (HF Inference Endpoint, vLLM, etc.)
when ``API_BASE_URL`` is set, otherwise falls back to ``MockLLMClient``
so tests and CPU-only laptops still work without API keys / GPU.

If the real endpoint errors (cold-start 503, timeout, unauthenticated),
we still return a CouncilDecision — generated by the deterministic mock —
so the React UI always shows specialist content instead of an empty panel.
The fallback decision's rationale prefixes carry the underlying error so
judges (and you) can see what went wrong.
"""

import logging
import os
import traceback

from fastapi import APIRouter, HTTPException

from app.council.llm import MockLLMClient, build_openai_client_from_env
from app.council.runner import Council
from app.models import CouncilDecision

logger = logging.getLogger(__name__)
router = APIRouter(tags=["council"])


def _make_client():
    if os.getenv("API_BASE_URL"):
        client = build_openai_client_from_env()
        logger.info("Council using real client: base_url=%s model=%s",
                    client.base_url, client.model)
        return client
    logger.info("Council using MockLLMClient (no API_BASE_URL set)")
    return MockLLMClient()


_real_council = Council(client=_make_client(), use_cache=True)
_mock_council = Council(client=MockLLMClient(), use_cache=False)


@router.get("/council", response_model=CouncilDecision)
async def get_council() -> CouncilDecision:
    import app.api.env as env_module

    env = env_module.current_env
    if not env.is_ready():
        raise HTTPException(
            status_code=409,
            detail="env not initialized or episode complete — call /reset first",
        )

    obs = env.current_observation()
    try:
        return await _real_council.run_async(obs)
    except Exception as e:
        # Endpoint cold-start, 503, network — fall back to mock so the UI
        # always renders. Annotate the rationale so the failure is visible.
        logger.warning("Real council failed (%s); falling back to mock.", e)
        logger.debug(traceback.format_exc())
        decision = await _mock_council.run_async(obs)
        suffix = f" [endpoint unavailable: {type(e).__name__}]"
        for v in decision.votes:
            v.rationale = (v.rationale or "") + suffix
        decision.rationale = (decision.rationale or "") + suffix
        return decision
